#pragma once

#include <stdint.h>
#include "fonts.h"

// I2c port as defined in main generated by CubeMx
#define SSD1306_I2C_PORT		I2C1
// I2c address
#define SSD1306_I2C_ADDR        0x78
// SSD1306 width in pixels
#define SSD1306_WIDTH           128
// SSD1306 LCD height in pixels
#define SSD1306_HEIGHT          64

//
//  Enumeration for screen colors
//
typedef enum {
  Black = 0x00, // Black color, no pixel
  White = 0x01  //Pixel is set. Color depends on LCD
} SSD1306_COLOR;

//
//  Struct to store transformations
//
typedef struct {
  uint16_t CurrentX;
  uint16_t CurrentY;
  uint8_t Inverted;
  uint8_t Initialized;
} SSD1306_t;

uint8_t ssd1306_init(void);
void ssd1306_fill(SSD1306_COLOR color);
void ssd1306_update_screen(void);
void ssd1306_draw_pixel(uint8_t x, uint8_t y, SSD1306_COLOR color);
char ssd1306_write_char(char ch, FontDef Font, SSD1306_COLOR color);
char ssd1306_write_string(char* str, FontDef Font, SSD1306_COLOR color);
void ssd1306_set_cursor(uint8_t x, uint8_t y);